name: example
description: A new Flutter project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.14.4 <3.0.0"
  flutter: ">=2.5.3"

dependencies:
  flutter:
    sdk: flutter

  animated_theme_switcher:
    path: ../
  shared_preferences: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

